import { maxWidthMedia } from '../../units/media';
import { hex, lessMap, px, theme } from '../../units/units';
import { generateLessConstants, processValue } from '../generatorLessConstants';

describe('generatorLessConstants', () => {
  it('generates less constants from values object', () => {
    expect(
      generateLessConstants({
        contentWidth: px(1024),
        lineHeightNormal: 1.2,
        screenDesktop: maxWidthMedia(px(1280), 'screen'),
        zIndex: lessMap({
          dropdown: 2,
          modal: 5,
        }),
        color: {
          text: theme({
            light: hex('#ffffff'),
            dark: hex('#000000'),
          }),
          link: {
            light: hex('#710e0e'),
            hover: hex('#b85e5e'),
          },
        },
      })
    ).toBe(`// This file was automatically generated by LessConstantsPlugin

@content-width: 1024px;

@line-height-normal: 1.2;

@screen-desktop: ~"screen and (max-width: 1280px)";

@z-index: {	//lessMap
	dropdown: 2;
	modal: 5;
}

@color-text: {	//theme
	light: #ffffff;
	dark: #000000;
}
@color-link-light: #710e0e;
@color-link-hover: #b85e5e;
`);
  });

  it('processes value with custom prefix', () => {
    expect(processValue('buttonSize', px(12), '@component')).toBe(
      '@component-button-size: 12px;\n'
    );
  });
});
