import { maxWidthMedia } from '../../units/media';
import { hex, lessMap, px, theme } from '../../units/units';
import { generateCssConstants, processValue } from '../generatorCssConstants';

describe('generatorCssConstants', () => {
  it('generates css constants for single theme', () => {
    expect(
      generateCssConstants(
        {
          contentWidth: px(1024),
          lineHeightNormal: 1.2,
          screenDesktop: maxWidthMedia(px(1280), 'screen'),
          zIndex: lessMap({
            dropdown: 2,
            modal: 5,
          }),
          color: {
            text: theme({
              light: hex('#ffffff'),
              dark: hex('#000000'),
            }),
            link: {
              hover: hex('#b85e5e'),
            },
          },
        },
        'light',
        ['light']
      )
    ).toBe(`// This file was automatically generated by LessConstantsPlugin
:root {
  --content-width: 1024px;
  --line-height-normal: 1.2;
  --z-index-dropdown: 2;
  --z-index-modal: 5;
  --color-text: #ffffff;
  --color-link-hover: #b85e5e;
}
`);
  });

  it('generates css constants for multiple themes', () => {
    expect(
      generateCssConstants(
        {
          contentWidth: px(1024),
          zIndex: lessMap({
            dropdown: 2,
            modal: 5,
          }),
          color: {
            text: theme({
              light: hex('#ffffff'),
              dark: hex('#000000'),
              contrast: hex('#ffcc00'),
            }),
            link: {
              hover: hex('#b85e5e'),
            },
          },
        },
        'light',
        ['light', 'dark', 'contrast']
      )
    ).toBe(`// This file was automatically generated by LessConstantsPlugin

:root {
  --content-width: 1024px;
  --z-index-dropdown: 2;
  --z-index-modal: 5;
  --color-link-hover: #b85e5e;
}

:root,
[data-theme="light"] {
  --color-text: #ffffff;
}

@media (prefers-color-scheme: dark) {
  :root[data-theme=""],
  :root:not([data-theme]) {
    --color-text: #000000;
  }
}

[data-theme="dark"] {
  --color-text: #000000;
}

[data-theme="contrast"] {
  --color-text: #ffcc00;
}
`);
  });

  it('generates css constants with dark default theme', () => {
    expect(
      generateCssConstants(
        {
          colorText: theme({
            light: hex('#ffffff'),
            dark: hex('#000000'),
          }),
        },
        'dark',
        ['light', 'dark']
      )
    ).toBe(`// This file was automatically generated by LessConstantsPlugin

:root {
${'  '}
}

:root,
[data-theme="dark"] {
  --color-text: #000000;
}

@media (prefers-color-scheme: light) {
  :root[data-theme=""],
  :root:not([data-theme]) {
    --color-text: #ffffff;
  }
}

[data-theme="light"] {
  --color-text: #ffffff;
}

`);
  });

  it('throws error for missing theme value', () => {
    expect(() =>
      generateCssConstants(
        {
          colorText: theme({
            light: hex('#ffffff'),
          }),
        },
        'light',
        ['light', 'dark', 'contrast']
      )
    ).toThrow('Missing themes in value for --color-text: dark, contrast');
  });

  it('processes value with custom prefix', () => {
    const groups = {
      all: [],
    };

    processValue({
      property: 'buttonSize',
      value: px(12),
      groups,
      defaultTheme: 'light',
      themes: ['light'],
      prefix: '--component',
    });

    expect(groups.all).toEqual(['--component-button-size: 12px;']);
  });
});
