import fs from 'fs';
import os from 'os';
import path from 'path';

import { createVerifyRegExps, getUsedConstants } from '../verify';

const lessConstants = `// This file was automatically generated by LessConstantsPlugin

@content-width: 1024px;

@z-index: {	//lessMap
	dropdown: 2;
	modal: 5;
}

@color-text: {	//theme
	light: #ffffff;
	dark: #000000;
}
@color-border: #b85e5e;
@mobile: ~"all and (max-width: 540px)";
`;

describe('verify', () => {
  it('creates verify regular expressions from less constants', () => {
    const verifyRegExps = createVerifyRegExps(lessConstants);

    expect(Object.keys(verifyRegExps)).toEqual([
      'content-width',
      'z-index[dropdown]',
      'z-index[modal]',
      'color-text',
      'color-border',
      'mobile',
    ]);
    expect('--content-width').toMatch(verifyRegExps['content-width'].css);
    expect('var(--content-width)').toMatch(verifyRegExps['content-width'].css);
    expect('@content-width').toMatch(verifyRegExps['content-width'].less);
    expect('@content-width;').toMatch(verifyRegExps['content-width'].less);
    expect('--content-width-x').not.toMatch(verifyRegExps['content-width'].css);
    expect('--content-width2').not.toMatch(verifyRegExps['content-width'].css);
    expect('@content-width-x').not.toMatch(verifyRegExps['content-width'].less);
    expect('@content-width2').not.toMatch(verifyRegExps['content-width'].less);

    expect('--z-index-dropdown').toMatch(
      verifyRegExps['z-index[dropdown]'].css
    );
    expect('@z-index[dropdown]').toMatch(
      verifyRegExps['z-index[dropdown]'].less
    );
    expect('--color-text').toMatch(verifyRegExps['color-text'].css);
    expect('@color-text[').toMatch(verifyRegExps['color-text'].less);
    expect('@color-text[light];').toMatch(verifyRegExps['color-text'].less);
  });

  it('gets used constants from file contents', async () => {
    const directory = await fs.promises.mkdtemp(
      path.join(os.tmpdir(), 'less-constants-verify-')
    );

    try {
      const filename = path.join(directory, 'component.less');
      const verifyRegExps = createVerifyRegExps(lessConstants);

      await fs.promises.writeFile(
        filename,
        `
.component {
  width: var(--content-width);
  z-index: @z-index[modal];
  color: @color-text[light];
  border-color: var(--color-border-custom);
  @media @mobile {}
}
.component2 {
    z-index: var(--z-index-dropdown);
}
`,
        'utf-8'
      );

      await expect(getUsedConstants(filename, verifyRegExps)).resolves.toEqual([
        'content-width',
        'z-index[dropdown]',
        'z-index[modal]',
        'color-text',
        'mobile',
      ]);
    } finally {
      await fs.promises.rm(directory, { recursive: true, force: true });
    }
  });
});
