import type { DefaultTheme, Themes, UnitValue } from './types';
import { slugify, isProperty, isMediaQuery, isLessMap, isTheme } from './utils';

/**
 * Generates content of CSS constants file from given object of values.
 */
function generateCssConstants(
  values: Record<string, UnitValue>,
  defaultTheme: DefaultTheme,
  themes: Themes
): string {
  // groups of css variables - for all themes, light theme, dark theme, ...
  const groups: Record<string, string[]> = {
    all: [] as string[],
  };

  if (themes.length > 1) {
    themes.forEach(theme => {
      groups[theme] = [] as string[];
    });
  }

  Object.keys(values).forEach(key => {
    processValue({
      property: key,
      value: values[key]!,
      groups,
      defaultTheme,
      themes,
    });
  });

  const cssVariables = generateGroups(groups, defaultTheme, themes);

  return `// This file was automatically generated by LessConstantsPlugin\n${cssVariables}`;
}

/**
 * Generates CSS output from variables sorted into groups.
 */
function generateGroups(
  groups: Record<string, string[]>,
  defaultTheme: DefaultTheme,
  themes: Themes
): string {
  // only 1 theme, simple:
  if (themes.length === 1) {
    return `:root {\n  ${groups.all!.join('\n  ')}\n}\n`;
  }

  // 2+ themes, light and dark and optional custom themes:
  const primarySystemTheme = defaultTheme;
  const secondarySystemTheme = defaultTheme === 'light' ? 'dark' : 'light';
  const customThemes = themes.filter(
    theme => theme !== 'light' && theme !== 'dark'
  );

  return `
:root {
  ${groups.all!.join('\n  ')}
}

:root,
[data-theme="${primarySystemTheme}"] {
  ${groups[primarySystemTheme]!.join('\n  ')}
}

@media (prefers-color-scheme: ${secondarySystemTheme}) {
  :root[data-theme=""],
  :root:not([data-theme]) {
    ${groups[secondarySystemTheme]!.join('\n    ')}
  }
}

[data-theme="${secondarySystemTheme}"] {
  ${groups[secondarySystemTheme]!.join('\n  ')}
}

${customThemes
  .map(
    theme => `[data-theme="${theme}"] {
  ${groups[theme]!.join('\n  ')}
}
`
  )
  .join('\n\n')}`;
}

/**
 * Processes recursively provided value which can be either object with other values or a constant.
 * Values are sorted into groups based on themes and are converted to CSS variables.
 */
function processValue({
  property,
  value,
  groups,
  defaultTheme,
  themes,
  prefix = '--',
}: {
  property: string;
  value: Record<string, UnitValue> | UnitValue;
  groups: Record<string, string[]>;
  defaultTheme: DefaultTheme;
  themes: Themes;
  prefix?: string;
}) {
  const subPrefix = prefix + (prefix.length > 2 ? '-' : '') + slugify(property);

  // Process media queries - skip them, they are not supported as CSS variables
  if (isMediaQuery(value)) {
    return;
  }

  // Process less maps
  // example: zIndex: lessMap({ key1: val1, key2: val2 }) => --z-index-key1: val1; --z-index-key2: val2;
  if (isLessMap(value)) {
    const lessMapValue = value.valueOf() as Record<string, UnitValue>;
    const lessMapKeys = Object.keys(lessMapValue);

    lessMapKeys.forEach(key => {
      groups.all!.push(
        `${subPrefix}-${slugify(key)}: ${lessMapValue[key]!.toString()};`
      );
    });
    return;
  }

  // Process themes
  if (isTheme(value)) {
    const themeValue = value.valueOf() as Record<string, UnitValue>;
    const themeKeys = Object.keys(themeValue);

    //check if there are all required themes in the value
    const missingThemes = themes.filter(theme => !themeKeys.includes(theme));

    if (missingThemes.length) {
      throw new Error(
        `Missing themes in value for ${subPrefix}: ${missingThemes.join(', ')}`
      );
    }

    // if we have only 1 theme, everything goes to "all" group
    // and we pick the desired value by default theme
    if (themes.length === 1) {
      groups.all!.push(
        `${subPrefix}: ${themeValue[defaultTheme]!.toString()};`
      );
    } else {
      themeKeys.forEach(themeKey => {
        if (themeKey in groups) {
          groups[themeKey]!.push(
            `${subPrefix}: ${themeValue[themeKey]!.toString()};`
          );
        }
      });
    }
    return;
  }

  // Process objects that are not property declarations - recursion
  if (value instanceof Object && !isProperty(value)) {
    Object.keys(value).forEach((subProperty: string) =>
      processValue({
        property: subProperty,
        value: (value as Record<string, UnitValue>)[subProperty]!,
        groups,
        defaultTheme,
        themes,
        prefix: subPrefix,
      })
    );
    return;
  }

  // Process property declarations and simple values
  groups.all!.push(`${subPrefix}: ${value.toString()};`);
}

export { generateCssConstants, generateGroups, processValue };
