import type { UnitValue } from './types';
import { slugify, isProperty, isMediaQuery, isLessMap, isTheme } from './utils';

/**
 * Generates less constants from given object of values.
 *
 * @param values
 * @returns { string }
 */
function generateLessConstants(values: Record<string, UnitValue>): string {
  const lessConstants = Object.keys(values)
    .map(key => {
      const value = processValue(key, values[key]!);

      return value;
    })
    .join('\n');

  return `// This file was automatically generated by LessConstantsPlugin\n\n${lessConstants}`;
}

/**
 * Processes provided value which can be either object or constant value recursively.
 *
 * @param property
 * @param value
 * @param prefix
 * @returns { string }
 */
function processValue(
  property: string,
  value: Record<string, UnitValue> | UnitValue,
  prefix = '@'
): string {
  // Generate label prefix
  const subPrefix = prefix + (prefix.length > 1 ? '-' : '') + slugify(property);

  // Process less maps
  if (isLessMap(value)) {
    return `${subPrefix}: {\t//lessMap\n${value.toString()}}\n`; //comment is needed to distinguish maps from themes in verification process
  }

  // Process themes
  if (isTheme(value)) {
    return `${subPrefix}: {\t//theme\n${value.toString()}}\n`; //comment is needed to distinguish themes from less maps in verification process
  }

  // Process objects that are not property declarations or mediaQueries
  if (value instanceof Object && !isProperty(value) && !isMediaQuery(value)) {
    return Object.keys(value)
      .map((subProperty: string) =>
        processValue(
          subProperty,
          (value as Record<string, UnitValue>)[subProperty]!,
          subPrefix
        )
      )
      .join('');
  }

  // Process property declarations, mediaQueries and simple values
  return `${subPrefix}: ${value.toString()};\n`;
}

export { generateLessConstants, processValue };
